POST http://localhost:3000/employee
Content-Type: application/json

{
    "employee_Name": "Tushar Deo",
    "employee_Post": "Product Engineer",
    "employee_Salary": 60000
}

###
POST http://localhost:3000/employee
Content-Type: application/json

{
    "employee_Name":"Aman Kumar",
    "employee_Post":"Associate Solution Engineer",
    "employee_Salary":35000
}

###

POST http://localhost:3000/employee
Content-Type: application/json

{
    "employee_Post":"Associate Solution Engineer",
    "employee_Salary":35000
}

###

POST http://localhost:3000/employee
Content-Type: application/json

{
    "employee_Name": "xyz abc",
    "employee_Post": "Product Manager",
    "employee_Salary": 60000
}

###

POST http://localhost:3000/employee
Content-Type: application/json

{
    "employee_Name": "abc xyz",
    "employee_Post": "Product Tester",
    "employee_Salary": 60000
}

###

GET http://localhost:3000/employee?employee_Salary=60000

###

GET http://localhost:3000/employee?employee_Salary=6000

###

GET http://localhost:3000/employee/all

###

GET http://localhost:3000/employee/64dc4531c3e2f92e65233d01

###

PATCH http://localhost:3000/employee/64dc4531c3e2f92e65233d01
Content-Type: application/json

{
    "employee_Salary":50000
}

###
PATCH http://localhost:3000/employee/64dc4531c3e2f92e65233d0
Content-Type: application/json

{
    "employee_Salary":500000
}

